name: Build and Push Docker Image and deploy to elastic beanstalk

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify your Python version

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Install EB CLI
        run: |
          pip install awsebcli  # Install Elastic Beanstalk CLI

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Modify as per your region
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build Docker image
#        run: |
#          docker build -t tmsasikumar/emotion_image_recognition:latest .
#
#      - name: Push Docker image
#        run: |
#          docker push tmsasikumar/emotion_image_recognition:latest

      - name: Initialize Elastic Beanstalk
        run: |
          eb init -p docker mood-final-v2 --region ap-south-1

      - name: Deploy to Elastic Beanstalk
        run:
          eb deploy --label $(date +%Y%m%d%H%M%S)